name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Rust

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: clippy, rustfmt
        
    - name: Build
      run: cargo +nightly build --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: target/debug/gff_parser    

  format:
    runs-on: ubuntu-latest
    name: Format Rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
          
      - name: Format
        run: cargo +nightly fmt --check
